import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { AuthService } from './auth';
import type { TransactionSql } from 'postgres';

type UserRow = { id: string; email: string; name: string; image: string | null; timezone: string; locale: string; isActive: boolean };
type WorkspaceRow = { id: string; name: string; slug: string; timezone: string; role: string; membershipStatus: string };
type MembershipRow = { workspaceId: string; userId: string; role: string; status: string };
type MemberRow = { userId: string; fullName: string; email: string; role: string; status: string };
type TeamRow = { id: string; workspace_id: string; name: string; description: string | null; manager_user_id: string | null; isActive: boolean; created_at: Date; updated_at: Date };
type TeamMutationInput = { name?: string; description?: string | null; managerUserId?: string | null; isActive?: boolean };
type TeamMemberRow = { userId: string; membershipRole: string };
type WorkspacePatchInput = { name?: string; timezone?: string };
type MembershipMutationInput = { role?: string; status?: string };
type MembershipUpsertInput = { userId: string; role: string; status: string };
const membershipStatuses = ['INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED'] as const;
const memberRoles = ['ADMIN', 'MANAGER', 'MEMBER', 'FIELD_WORKER'] as const;

@Injectable()
export class FlozService {
  constructor(@Inject(AuthService) private readonly authService: AuthService) {}

  private get sql() { return this.authService.database.sql; }

  async user(id: string): Promise<UserRow | null> { return ((await this.sql<UserRow[]>`SELECT id, email, name, image, timezone, locale, is_active AS "isActive" FROM users WHERE id = ${id} LIMIT 1`)[0] ?? null) as UserRow | null; }
  async userByEmail(email: string): Promise<UserRow | null> { return ((await this.sql<UserRow[]>`SELECT id, email, name, image, timezone, locale, is_active AS "isActive" FROM users WHERE lower(email) = lower(${email}) LIMIT 1`)[0] ?? null) as UserRow | null; }
  async updateUser(id: string, input: { name?: string; timezone?: string; locale?: string; image?: string | null }): Promise<UserRow | null> { return ((await this.sql<UserRow[]>`UPDATE users SET name = COALESCE(${input.name ?? null}, name), timezone = COALESCE(${input.timezone ?? null}, timezone), locale = COALESCE(${input.locale ?? null}, locale), image = CASE WHEN ${input.image === undefined} THEN image ELSE ${input.image ?? null} END, updated_at = NOW() WHERE id = ${id} RETURNING id, email, name, image, timezone, locale, is_active AS "isActive"`)[0] ?? null) as UserRow | null; }
  async workspacesFor(userId: string, activeOnly = false): Promise<WorkspaceRow[]> { return await this.sql<WorkspaceRow[]>`SELECT w.id, w.name, w.slug, w.timezone, r.code AS role, wm.status AS "membershipStatus" FROM workspace_memberships wm INNER JOIN workspaces w ON w.id = wm.workspace_id INNER JOIN roles r ON r.id = wm.role_id WHERE wm.user_id = ${userId}${activeOnly ? this.sql` AND wm.status = 'ACTIVE' AND w.is_active = true` : this.sql``}`; }
  async workspace(id: string): Promise<{ id: string; name: string; slug: string; timezone: string } | null> { return ((await this.sql<{ id: string; name: string; slug: string; timezone: string }[]>`SELECT id, name, slug, timezone FROM workspaces WHERE id = ${id} LIMIT 1`)[0] ?? null) as { id: string; name: string; slug: string; timezone: string } | null; }
  async membership(userId: string, workspaceId: string): Promise<MembershipRow | null> { return ((await this.sql<MembershipRow[]>`SELECT wm.workspace_id AS "workspaceId", wm.user_id AS "userId", r.code AS role, wm.status FROM workspace_memberships wm INNER JOIN roles r ON r.id = wm.role_id WHERE wm.user_id = ${userId} AND wm.workspace_id = ${workspaceId} AND wm.status = 'ACTIVE' LIMIT 1`)[0] ?? null) as MembershipRow | null; }
  async managerMembership(userId: string, workspaceId: string) { return await this.sql`SELECT 1 FROM workspace_memberships wm INNER JOIN roles r ON r.id = wm.role_id WHERE wm.user_id = ${userId} AND wm.workspace_id = ${workspaceId} AND wm.status = 'ACTIVE' AND r.code IN ('MANAGER', 'ADMIN') LIMIT 1`; }
  async managedTeamIds(workspaceId: string, userId: string): Promise<string[]> { return (await this.sql<{ id: string }[]>`SELECT id FROM teams WHERE workspace_id = ${workspaceId} AND manager_user_id = ${userId} AND is_active = true`).map((team) => team.id); }
  async lockWorkspace(sql: TransactionSql, workspaceId: string) { const locked = (await sql<{ id: string }[]>`SELECT id FROM workspaces WHERE id = ${workspaceId} FOR UPDATE`)[0]; if (!locked) throw new NotFoundException('NOT_FOUND'); return locked.id; }
  async patchWorkspace(workspaceId: string, input: WorkspacePatchInput) { return await this.sql.begin(async (sql: TransactionSql) => { await this.lockWorkspace(sql, workspaceId); const updated = (await sql<{ id: string; name: string; slug: string; timezone: string }[]>`UPDATE workspaces SET name = COALESCE(${input.name ?? null}, name), timezone = COALESCE(${input.timezone ?? null}, timezone), updated_at = NOW() WHERE id = ${workspaceId} RETURNING id, name, slug, timezone`)[0]; if (!updated) throw new NotFoundException('NOT_FOUND'); return updated; }); }
  async members(workspaceId: string): Promise<MemberRow[]> { return await this.sql<MemberRow[]>`SELECT wm.user_id AS "userId", u.name AS "fullName", u.email, r.code AS role, wm.status FROM workspace_memberships wm INNER JOIN users u ON u.id = wm.user_id INNER JOIN roles r ON r.id = wm.role_id WHERE wm.workspace_id = ${workspaceId}`; }
  async addMember(workspaceId: string, input: MembershipUpsertInput): Promise<MemberRow> { return await this.sql.begin(async (sql: TransactionSql) => { await this.lockWorkspace(sql, workspaceId); if (!membershipStatuses.includes(input.status as typeof membershipStatuses[number])) throw new BadRequestException('VALIDATION_ERROR'); const existing = (await sql<MembershipRow[]>`SELECT wm.workspace_id AS "workspaceId", wm.user_id AS "userId", r.code AS role, wm.status FROM workspace_memberships wm INNER JOIN roles r ON r.id = wm.role_id WHERE wm.workspace_id = ${workspaceId} AND wm.user_id = ${input.userId} FOR UPDATE`)[0] ?? null; const role = await this.roleId(sql, input.role); if (existing) throw new ConflictException('DUPLICATE_EMAIL'); if (!(await sql`SELECT id FROM users WHERE id=${input.userId}`)[0]) throw new BadRequestException('CROSS_WORKSPACE_REFERENCE'); if ((await this.activeAdmins(sql, workspaceId))[0].count < 1) throw new ConflictException('LAST_ACTIVE_ADMIN'); await sql`INSERT INTO workspace_memberships(workspace_id,user_id,role_id,status) VALUES(${workspaceId},${input.userId},${role},${input.status})`; const member = await this.memberByUserId(sql, workspaceId, input.userId); if (!member) throw new NotFoundException('NOT_FOUND'); return member; }); }
  async updateMember(workspaceId: string, userId: string, input: MembershipMutationInput): Promise<MemberRow> { return await this.sql.begin(async (sql: TransactionSql) => { await this.lockWorkspace(sql, workspaceId); const current = (await sql<{ roleId: string; status: string }[]>`SELECT role_id AS "roleId", status FROM workspace_memberships WHERE workspace_id = ${workspaceId} AND user_id = ${userId} FOR UPDATE`)[0]; if (!current) throw new NotFoundException('NOT_FOUND'); const nextRole = input.role ? await this.roleId(sql, input.role) : current.roleId; const nextStatus = input.status ?? current.status; if (!membershipStatuses.includes(nextStatus as typeof membershipStatuses[number])) throw new BadRequestException('VALIDATION_ERROR'); await this.ensureMemberMutationAllowed(sql, workspaceId, userId, nextRole, nextStatus); await sql`UPDATE workspace_memberships SET role_id=${nextRole}, status=${nextStatus}, updated_at=NOW() WHERE workspace_id=${workspaceId} AND user_id=${userId}`; const member = await this.memberByUserId(sql, workspaceId, userId); if (!member) throw new NotFoundException('NOT_FOUND'); return member; }); }
  async listTeams(workspaceId: string): Promise<TeamRow[]> { return await this.sql<TeamRow[]>`SELECT id, workspace_id, name, description, manager_user_id, is_active AS "isActive", created_at, updated_at FROM teams WHERE workspace_id = ${workspaceId}`; }
  private async roleId(sql: TransactionSql, code: string) { const role = (await sql<{ id: string }[]>`SELECT id FROM roles WHERE code = ${code} LIMIT 1`)[0]; if (!role || !memberRoles.includes(code as typeof memberRoles[number])) throw new BadRequestException('VALIDATION_ERROR'); return role.id; }
  private async memberByUserId(sql: TransactionSql, workspaceId: string, userId: string): Promise<MemberRow | null> { return (await sql<MemberRow[]>`SELECT wm.user_id AS "userId", u.name AS "fullName", u.email, r.code AS role, wm.status FROM workspace_memberships wm INNER JOIN users u ON u.id = wm.user_id INNER JOIN roles r ON r.id = wm.role_id WHERE wm.workspace_id = ${workspaceId} AND wm.user_id = ${userId}`)[0] ?? null; }
  private async activeAdmins(sql: TransactionSql, workspaceId: string) { return await sql<{ count: number }[]>`SELECT COUNT(*)::int AS count FROM workspace_memberships wm INNER JOIN roles r ON r.id = wm.role_id WHERE wm.workspace_id = ${workspaceId} AND wm.status = 'ACTIVE' AND r.code = 'ADMIN'`; }
  private async activeTeamManagers(sql: TransactionSql, workspaceId: string, userId: string) { return await sql<{ count: number }[]>`SELECT COUNT(*)::int AS count FROM teams WHERE workspace_id = ${workspaceId} AND is_active = true AND manager_user_id = ${userId}`; }
  private async ensureMemberMutationAllowed(sql: TransactionSql, workspaceId: string, userId: string, nextRole: string, nextStatus: string) { const admins = await this.activeAdmins(sql, workspaceId); const managed = await this.activeTeamManagers(sql, workspaceId, userId); const currentRole = (await sql<{ role: string }[]>`SELECT r.code AS role FROM workspace_memberships wm INNER JOIN roles r ON r.id = wm.role_id WHERE wm.workspace_id = ${workspaceId} AND wm.user_id = ${userId}`)[0]?.role; const nextRoleCode = (await sql<{ code: string }[]>`SELECT code FROM roles WHERE id=${nextRole}`)[0]?.code; const willBeActiveAdmin = nextStatus === 'ACTIVE' && nextRoleCode === 'ADMIN'; const remainingAdmins = admins[0].count - (currentRole === 'ADMIN' && !willBeActiveAdmin ? 1 : 0); if (remainingAdmins < 1) throw new ConflictException('LAST_ACTIVE_ADMIN'); if (managed[0].count > 0 && (nextStatus !== 'ACTIVE' || !['ADMIN','MANAGER'].includes(nextRoleCode))) throw new ConflictException('ACTIVE_TEAM_MANAGER'); }
  async team(workspaceId: string, id: string): Promise<TeamRow | null> { return ((await this.sql<TeamRow[]>`SELECT id, workspace_id, name, description, manager_user_id, is_active AS "isActive", created_at, updated_at FROM teams WHERE id = ${id} AND workspace_id = ${workspaceId} LIMIT 1`)[0] ?? null) as TeamRow | null; }
  async createTeam(workspaceId: string, input: { name: string; description: string | null; managerUserId: string | null }): Promise<TeamRow> { return await this.sql.begin(async (sql: TransactionSql) => { await this.lockWorkspace(sql, workspaceId); if (input.managerUserId && !(await this.isActiveManager(sql, workspaceId, input.managerUserId))) throw new BadRequestException('INVALID_MANAGER'); return (await sql<TeamRow[]>`INSERT INTO teams (workspace_id, name, description, manager_user_id) VALUES (${workspaceId}, ${input.name}, ${input.description}, ${input.managerUserId}) RETURNING id, workspace_id, name, description, manager_user_id, is_active AS "isActive", created_at, updated_at`)[0]; }); }
  async updateTeam(workspaceId: string, id: string, input: TeamMutationInput): Promise<TeamRow> { return await this.sql.begin(async (sql: TransactionSql) => { await this.lockWorkspace(sql, workspaceId); const current = (await sql<{ managerUserId: string | null; isActive: boolean }[]>`SELECT manager_user_id AS "managerUserId", is_active AS "isActive" FROM teams WHERE id = ${id} AND workspace_id = ${workspaceId} FOR UPDATE`)[0]; if (!current) throw new NotFoundException('NOT_FOUND'); const nextManagerUserId = input.managerUserId === undefined ? current.managerUserId : input.managerUserId; const nextIsActive = input.isActive === undefined ? current.isActive : input.isActive; if (nextIsActive && nextManagerUserId && !(await this.isActiveManager(sql, workspaceId, nextManagerUserId))) throw new ConflictException('INVALID_MANAGER'); const updated = input.managerUserId === undefined ? (await sql<TeamRow[]>`UPDATE teams SET name = COALESCE(${input.name ?? null}, name), description = COALESCE(${input.description ?? null}, description), is_active = ${nextIsActive}, updated_at = NOW() WHERE id = ${id} AND workspace_id = ${workspaceId} RETURNING id, workspace_id, name, description, manager_user_id, is_active AS "isActive", created_at, updated_at`)[0] : (await sql<TeamRow[]>`UPDATE teams SET name = COALESCE(${input.name ?? null}, name), description = COALESCE(${input.description ?? null}, description), manager_user_id = ${input.managerUserId ?? null}, is_active = ${nextIsActive}, updated_at = NOW() WHERE id = ${id} AND workspace_id = ${workspaceId} RETURNING id, workspace_id, name, description, manager_user_id, is_active AS "isActive", created_at, updated_at`)[0]; if (!updated) throw new NotFoundException('NOT_FOUND'); return updated; }); }
  async teamMembers(teamId: string): Promise<TeamMemberRow[]> { return await this.sql<TeamMemberRow[]>`SELECT tm.user_id AS "userId", tm.membership_role AS "membershipRole" FROM team_memberships tm INNER JOIN teams t ON t.id=tm.team_id INNER JOIN workspace_memberships wm ON wm.workspace_id=t.workspace_id AND wm.user_id=tm.user_id WHERE tm.team_id = ${teamId} AND tm.left_at IS NULL AND wm.status='ACTIVE'`; }
  async addTeamMember(workspaceId: string, teamId: string, userId: string): Promise<{ userId: string; membershipRole: string }> { return await this.sql.begin(async (sql: TransactionSql) => { await this.lockWorkspace(sql, workspaceId); const team = (await sql<{ isActive: boolean }[]>`SELECT is_active AS "isActive" FROM teams WHERE id=${teamId} AND workspace_id=${workspaceId} FOR UPDATE`)[0]; if (!team) throw new NotFoundException('NOT_FOUND'); if (!team.isActive) throw new ConflictException('TEAM_ARCHIVED'); return (await sql<{ userId: string; membershipRole: string }[]>`INSERT INTO team_memberships (team_id, user_id) VALUES (${teamId}, ${userId}) ON CONFLICT (team_id, user_id) DO UPDATE SET left_at = NULL, joined_at = NOW() RETURNING user_id AS "userId", membership_role AS "membershipRole"`)[0]; }); }
  async isActiveManager(sql: TransactionSql, workspaceId: string, userId: string) { return (await sql<{ count: number }[]>`SELECT COUNT(*)::int AS count FROM workspace_memberships wm INNER JOIN roles r ON r.id = wm.role_id WHERE wm.workspace_id = ${workspaceId} AND wm.user_id = ${userId} AND wm.status = 'ACTIVE' AND r.code IN ('ADMIN', 'MANAGER')`)[0].count > 0; }
  async removeTeamMember(workspaceId: string, teamId: string, userId: string) { await this.sql.begin(async (sql: TransactionSql) => { await this.lockWorkspace(sql, workspaceId); await sql`UPDATE team_memberships SET left_at = NOW() WHERE team_id = ${teamId} AND user_id = ${userId} AND EXISTS (SELECT 1 FROM teams WHERE id = ${teamId} AND workspace_id = ${workspaceId})`; }); }
}
